version: "3.9"

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: chatapp-rabbitmq
    ports:
      - ${RABBITMQ_PORT:-5672}:5672
      - ${RABBITMQ_MANAGEMENT_PORT:-15672}:15672
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER:-chatapp_user}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD:-chatapp_password}
    networks:
      - chatapp-network

  auth-db:
    image: mysql:8.0
    container_name: chatapp-auth-db
    environment:
     MYSQL_ROOT_PASSWORD: ${AUTH_DB_ROOT_PASSWORD:-root_password}
     MYSQL_DATABASE: ${AUTH_DB_NAME:-chatapp_auth-service}
     MYSQL_USER: ${AUTH_DB_USER:-chatapp_auth_user}
     MYSQL_PASSWORD: ${AUTH_DB_PASSWORD:-chatapp_auth_password}
    command: ["mysqld","--default-authentication-plugin=mysql_native_password"]
    ports:
      - ${AUTH_DB_PORT:-3307}:3306
    volumes:
      - auth-db-data:/var/lib/mysql
    networks:
      - chatapp-network

volumes:
  auth-db-data:

networks:
  chatapp-network:
    driver: bridge
